### ISSUE TITLE
webpack build to emit errors in sane way

### ISSUE THREAD

**Issue by maraisr** [theKashey/holistic-image#4]
Be very cool if webpack could break the build if `--validate` would for instance fail, as in do derived files exist or not. This would be a client-side error emitted in the loader in `mode: development` and a blatant break-the-build in `mode: production`.

In the same was a Relay emits the `if (__DEV__ && hash === computedHash) { throw new Error(); }` during its dev-mode.

**Comment by theKashey** [comment]
Now it can emit errors or autogenerate missing image
✅  in v1.1.1
